Text = "Hello world!" #You can change the Text
ruler1,rulerA = "1" , "A"
ruler2,rulerB = ruler1 + " 2 " +ruler1 , rulerA + " B " +rulerA
ruler3,rulerC = ruler2 + " 3 " +ruler2 , rulerB + " C " +rulerB
ruler4,rulerD = ruler3 + " 4 " +ruler3 , rulerC + " D " +rulerC
ruler5,rulerE = ruler4 + " 5 " +ruler4 , rulerD + " E " +rulerD
print("%32s"%ruler1,"%61s"%rulerA)
print("%32s"%ruler1,"%61s"%rulerA)
print("%34s"%ruler2,"%61s"%rulerB)
print("%34s"%ruler2,"%61s"%rulerB)
print("%38s"%ruler3,"%61s"%rulerC)
print("%38s"%ruler3,"%61s"%rulerC)
print("%46s"%ruler4,"%61s"%rulerD)
print("%46s"%ruler4,"%61s"%rulerD)
print("", ruler5, rulerE)
print("%46s"%ruler4,"%61s"%rulerD)
print("%46s"%ruler4,"%61s"%rulerD)
print("%38s"%ruler3,"%61s"%rulerC)
print("%38s"%ruler3,"%61s"%rulerC)
print("%34s"%ruler2,"%61s"%rulerB)
print("%34s"%ruler2,"%61s"%rulerB)
print("%32s"%ruler1,"%61s"%rulerA)
print("%32s"%ruler1,"%61s"%rulerA)
print("%68s"%Text)
print("%32s"%ruler1,"%61s"%rulerA)
print("%32s"%ruler1,"%61s"%rulerA)
print("%34s"%ruler2,"%61s"%rulerB)
print("%34s"%ruler2,"%61s"%rulerB)
print("%38s"%ruler3,"%61s"%rulerC)
print("%38s"%ruler3,"%61s"%rulerC)
print("%46s"%ruler4,"%61s"%rulerD)
print("%46s"%ruler4,"%61s"%rulerD)
print("", ruler5, rulerE)
print("%46s"%ruler4,"%61s"%rulerD)
print("%46s"%ruler4,"%61s"%rulerD)
print("%38s"%ruler3,"%61s"%rulerC)
print("%38s"%ruler3,"%61s"%rulerC)
print("%34s"%ruler2,"%61s"%rulerB)
print("%34s"%ruler2,"%61s"%rulerB)
print("%32s"%ruler1,"%61s"%rulerA)
print("%32s"%ruler1,"%61s"%rulerA)
input()

'''
print("                                ",rulerA)
print("                                ",rulerA)
print("                              ", rulerB)
print("                              ", rulerB)
print("                          ", rulerC)
print("                          ", rulerC)
print("                  ", rulerD)
print("                  ", rulerD)
print("  ", rulerE)
print("                  ", rulerD)
print("                  ", rulerD)
print("                          ", rulerC)
print("                          ", rulerC)
print("                              ", rulerB)
print("                              ", rulerB)
print("                                ",rulerA)
print("                                ",rulerA)
input()
'''